POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Life is beautiful",
  "author": "Long Mai",
  "url": "sdsdff",
  "likes": "24",
  "userId":"603633612856cc1038a6715f"
}